### ISSUE TITLE
TypeError: Object [object Object] has no method 'updateFrom'

### ISSUE THREAD

**Issue by getnick80** [getnick80/hipster-shop#9]
Sentry Issue: [JIRA-INTEGRATION-TEST-1](https://sentry.io/self-p7/jira-integration-test/issues/736286062/)

```
TypeError: Object [object Object] has no method 'updateFrom'
  at poll (../../sentry/scripts/views.js:389:46)
  at merge (../../sentry/scripts/views.js:268:16)
  at member (../../sentry/scripts/views.js:283:50)

This is an example JavaScript exception
```

**Comment by getnick80** [comment]
➤ Nick Skinner commented:

please update asap

**Comment by getnick80** [comment]
➤ Sentry commented:

Nick Skinner wrote:

{quote}this needs to be assigned{quote}

**Comment by getnick80** [comment]
➤ Sentry commented:

Nick Skinner wrote:

{quote}update for azure devops{quote}
